default: &default
  adapter: postgresql
  pool: 5
  port: 5432
  timeout: 5000
  encoding: unicode
  username: rodya
  password: rodya

development:
  <<: *default
  database: shop_back_development

test:
  <<: *default
  database: shop_back_test
